### ISSUE TITLE
error in traci.gui.screenshot

### ISSUE THREAD

**Issue by wges** [pipeacosta/traci4matlab#10]
The usage of traci.gui.screenshot e.g. in traci_test2.m leads to an error:
call:
`traci.gui.screenshot('View #0','passedvehicle.bmp')`

error:

> Error using traci.sendExact (line 46)
> 45  204  255 Error Screenshot requires a compound object.
> 
> 
> Error in traci.sendStringCmd (line 18)
> traci.sendExact();
> 
> Error in traci.gui.screenshot (line 14)
> traci.sendStringCmd(constants.CMD_SET_GUI_VARIABLE, constants.VAR_SCREENSHOT, viewID, filename);
> 
> Error in traci_test2 (line 833)
>     traci.gui.screenshot('View #0','passedvehicle.bmp')

**Comment by frrrizzz** [comment]
Fixed in commit 0e77dd5
