### ISSUE TITLE
Error: Could not build output file 'C:\Program Files (x86)\Eclipse\Sumo\doc\tutorial\traci_tls\data\cross.out' (Permission denied).

### ISSUE THREAD

**Issue by tonmoy-TS** [pipeacosta/traci4matlab#23]
Hi, I installed traci4matlab successfully and was able to run the example: inter_palmas.m and traci_test.m successfully.
However, whenever I am trying to run the test2.m script, the gui opens, but shows this following error

```
----------------------------------------------------------------------------------------
***Starting server on port 8813 ***
Loading net-file from 'C:\Program Files (x86)\Eclipse\Sumo\doc\tutorial\traci_tls\data\cross.net.xml' ... done (13ms).
Loading additional-files from 'C:\Program Files (x86)\Eclipse\Sumo\doc\tutorial\traci_tls\data\cross.det.xml' ... 
Error: Could not build output file 'C:\Program Files (x86)\Eclipse\Sumo\doc\tutorial\traci_tls\data\cross.out' (Permission denied).
Loading of additional-files failed.
Quitting (on error).
```
![Screenshot 2022-11-15 011811](https://user-images.githubusercontent.com/70789929/201854393-33e3f132-46fe-4b93-afc2-a0fdd4ef4134.png)

And then if I close the gui, the error follows in the matlab command prompt:

```
Error using traci.recvExact
Java exception occurred:
java.net.SocketException: Connection reset

	at java.net.SocketInputStream.read(SocketInputStream.java:210)

	at java.net.SocketInputStream.read(SocketInputStream.java:141)

	at java.net.SocketInputStream.read(SocketInputStream.java:224)

	at java.io.DataInputStream.readInt(DataInputStream.java:387)


Error in traci.sendExact (line 23)
result = traci.recvExact();

Error in traci.getVersion (line 23)
result = traci.sendExact();

Error in traci.start (line 65)
[traciVersion,sumoVersion] = traci.getVersion();

Error in traci_test2 (line 57)
traci.start(['sumo-gui -c ' '"' scenarioPath '"' ' --start']);
```

Does anyone know how to solve this issue ?
TIA

**Comment by tonmoy-TS** [comment]
I figured it out. The problem was with the file permission and I fixed it by allowing permission to the relevant user profile.
You could follow these steps (in Windows):
- Right click on the installation folder (C:/.../Eclipse/Sumo), go to Properties.
- In Properties, select the 'Security' tab. You would see the list of the user profiles, and their Permissions respectively.
- Allow permission to the user profiles you'd be using to run SUMO (click Allow) > Apply > OK.

Note that, the files are protected to make sure that you accidently don't make any unwanted changes while modifying the codes. To avoid that, you could also copy the codes to a different directory other than the installation folder (you might need to change the environment variables accordingly as well).

**Comment by Linda598-prog** [comment]
Loading configuration... done.
***Starting server on port 48535 ***
Loading net-file from '/tmp/flow/debug/cfg/CoTV_1x1grid_20240522-1050491716346249.6291587.net.xml'... done (2ms).
Loading additional-files from '/tmp/flow/debug/cfg/CoTV_1x1grid_20240522-1050491716346249.6291587.add.xml'... done (23ms).
Loading done.
Simulation started with time: 0.00
Error: Could not build output file 'None/CoTV_1x1grid_20240522-1050491716346249.6291587-3-ssm.xml' (没有那个文件或目录).
Quitting (on error).   
in ubuntu ,who know how to solve this question
![2024-05-20 15-13-00 的屏幕截图](https://github.com/pipeacosta/traci4matlab/assets/164609695/430cb25b-8375-445d-b3f6-59e3f3f57385)
