### ISSUE TITLE
The command line  could not be closed while testing the "" by using the NEW release version of TRACI4MATLAB

### ISSUE THREAD

**Issue by JaneCheung** [pipeacosta/traci4matlab#3]
Hi, Andres Acosta
Thanks for updating  the API!

There is some problem while I was trying to run the test_traci. m after I downloaded the new release version of TRACTI4MATALB.
The problem is shown below:
![image](https://user-images.githubusercontent.com/39317241/50660472-7b85f180-0f65-11e9-9f83-3595f6d1cf8b.png)
The other two test examples could run very as the description in the PDF document.

Could you give some suggestion about the problem.

**Comment by pipeacosta** [comment]
Thanks for pointing out this issue. Changing the port number on line 21 of the traci_test.m file to 8813 should work:
sumoArgs = '--remote-port 8813 --xml-validation never&';

Best Regards.

**Comment by JaneCheung** [comment]
Andres Acosta, thanks so much!
The test_traci. m work well after modifying the port number!

Best regards!

**Comment by pipeacosta** [comment]
Dear Jane Cheung.

I also updated the test file.

Best Regards.
